### ISSUE TITLE
Commented out code hanging around

### ISSUE THREAD

**Issue by Kingitus** [KaurSamuel/Hello-World-STM32#1]
Commented code hanging about in Main.cpp.

     /*  delay(200);
      digitalWrite(LED_BUILTIN, LOW);
      delay(200);
      digitalWrite(LED_BUILTIN, HIGH);
    */

What is the purpose of this code?

**Comment by KaurSamuel** [comment]
Shut

**Comment by KaurSamuel** [comment]
Expanded comment
